package com.myradio.deepradio

data class RadioStation(
    val name: String,
    val streamUrl: String,
    val iconResId: Int,
    val apiUrl: String,
    val categories: List<String>,
    var isFavorite: Boolean = false,
    val originalIndex: Int
) {
    companion object {
        fun createSampleStations() = listOf(
            RadioStation("Hit FM Українські хіти", "https://online.hitfm.ua/HitFM_Ukr_HD", R.drawable.icon1, "https://o.tavrmedia.ua/hitu", listOf("Pop", "Ukr"), false, 0),
            RadioStation("Hit FM Найбільші хіти", "https://online.hitfm.ua/HitFM_Best_HD", R.drawable.icon2, "https://o.tavrmedia.ua/hitb", listOf("Pop", "Oldschool"), false, 1),
            RadioStation("Hit FM Сучасні хіти", "https://online.hitfm.ua/HitFM_Top_HD", R.drawable.icon3, "https://o.tavrmedia.ua/hitt", listOf("Pop", "Dance"), false, 2),
            RadioStation("Kiss FM", "https://online.kissfm.ua/KissFM_HD", R.drawable.icon4, "https://o.tavrmedia.ua/kiss", listOf("EDM", "Dance"), false, 3),
            RadioStation("Kiss FM Digital", "https://online.kissfm.ua/KissFM_Digital_HD", R.drawable.icon5, "https://o.tavrmedia.ua/kissdigital", listOf("EDM", "Techno"), false, 4),
            RadioStation("Megamix", "https://radiorecord.hostingradio.ru/mix96.aacp", R.drawable.icon6, "https://www.radiorecord.ru/api/station/history/?id=520", listOf("Dance", "Remix"), false, 5),
            RadioStation("KissFM Ukrainian", "https://online.kissfm.ua/KissFM_Ukr_HD", R.drawable.icon7, "https://o.tavrmedia.ua/kissukr", listOf("Pop", "Ukr"), false, 6),
            RadioStation("DJ FM", "https://cast.fex.net/djfm_x", R.drawable.icon8, "https://scraper2.onlineradiobox.com/ua.dj.fm?l=0", listOf("EDM", "House"), false, 7),
            RadioStation("Record Gold", "https://radiorecord.hostingradio.ru/gold96.aacp", R.drawable.icon9, "https://www.radiorecord.ru/api/station/history/?id=506", listOf("Oldschool", "Pop"), false, 8),
            RadioStation("Record Phonk", "https://radiorecord.hostingradio.ru/phonk96.aacp", R.drawable.icon10, "https://www.radiorecord.ru/api/station/history/?id=43174", listOf("Bass", "Rap/Urban"), false, 9),
            RadioStation("Record Remix", "https://radiorecord.hostingradio.ru/rmx96.aacp", R.drawable.icon11, "https://www.radiorecord.ru/api/station/history/?id=548", listOf("EDM", "Dance"), false, 10),
            RadioStation("Record Trap", "https://radiorecord.hostingradio.ru/trap96.aacp", R.drawable.icon12, "https://www.radiorecord.ru/api/station/history/?id=552", listOf("EDM", "Bass"), false, 11),
            RadioStation("Record Club", "https://radiorecord.hostingradio.ru/club96.aacp", R.drawable.icon13, "https://www.radiorecord.ru/api/station/history/?id=529", listOf("Club", "EDM"), false, 12),
            RadioStation("Record EMD Classics", "https://radiorecord.hostingradio.ru/edmhits96.aacp", R.drawable.icon14, "https://www.radiorecord.ru/api/station/history/?id=506", listOf("EDM", "Oldschool"), false, 13),
            RadioStation("Record Russian Mix", "https://radiorecord.hostingradio.ru/rus96.aacp", R.drawable.icon15, "https://www.radiorecord.ru/api/station/history/?id=537", listOf("Rus", "Remix"), false, 14),
            RadioStation("Record House Hits", "https://radiorecord.hostingradio.ru/househits96.aacp", R.drawable.icon16, "https://www.radiorecord.ru/api/station/history/?id=506", listOf("House", "EDM"), false, 15),
            RadioStation("НашеРадіо Топ 1ОО", "https://online.nasheradio.ua/NasheRadio_Ukr_HD", R.drawable.icon17, "https://o.tavrmedia.ua/nasheradio3ukr", listOf("Pop", "Ukr"), false, 16),
            RadioStation("Marusya Default", "https://radio-holding.ru:9433/marusya_default", R.drawable.icon18, "https://rbtrack.ru/whoplay/20122021/921.json?cache7=1716689040", listOf("Pop", "Rus"), false, 17),
            RadioStation("Like FM Black", "https://srv12.gpmradio.ru:8443/stream/air/aac/64/219", R.drawable.icon19, "https://101.ru/api/channel/getTrackOnAir/219/channel/?dataFormat=json", listOf("Rap/Urban", "Bass"), false, 18),
            RadioStation("Europaplus ru", "https://ep256.hostingradio.ru:8052/europaplus256.mp3", R.drawable.icon20, "https://api.instant.audio/data/playlist/74/evropa-plus-100-5-fm", listOf("Pop", "Rus"), false, 19),
            RadioStation("Люкс ФМ", "https://icecast.luxnet.ua/lux", R.drawable.icon21, "https://api.instant.audio/data/playlist/140/lux-fm", listOf("Pop", "Ukr"), false, 20),
            RadioStation("Perets FM", "https://radio.urg.ua/radio-stilnoe", R.drawable.icon22, "https://scraper2.onlineradiobox.com/ua.stilnoe.fm?l=0", listOf("Pop", "Rus"), false, 21),
            RadioStation("RadioRecord ru", "https://radiorecord.hostingradio.ru/rr_main96.aacp", R.drawable.icon23, "https://www.radiorecord.ru/api/station/history/?id=15016", listOf("EDM", "Rus"), false, 22),
            RadioStation("Tim FM", "https://tim-fm.tim.ua/chemp3", R.drawable.icon24, "https://scraper2.onlineradiobox.com/ua.europaplusdp?l=0", listOf("Pop", "Rus"), false, 23),
            RadioStation("RadioBayraktar", "https://online.radiobayraktar.ua/RadioBayraktar_HD", R.drawable.icon25, "https://o.tavrmedia.ua/radio3bayraktar", listOf("Pop", "Ukr"), false, 24),
            RadioStation("Workout", "https://radiorecord.hostingradio.ru/workout96.aacp", R.drawable.icon26, "https://www.radiorecord.ru/api/station/history/?id=43339", listOf("EDM", "Dance"), false, 25),
            RadioStation("ZaycevFM Rus", "https://abs.zaycev.fm/rus256k", R.drawable.icon27, "https://api.zaycev.fm/api/v1/channels/rus/latest?page=1&limit=5", listOf("Pop", "Rus"), false, 26),
            RadioStation("ZaycevFM Pop", "https://abs.zaycev.fm/pop256k", R.drawable.icon28, "https://api.zaycev.fm/api/v1/channels/pop/latest?page=1&limit=5", listOf("Pop", "Dance"), false, 27),
            RadioStation("Future Rave", "https://radiorecord.hostingradio.ru/futurerave96.aacp", R.drawable.icon29, "https://www.radiorecord.ru/api/station/history/?id=43454", listOf("Dance", "EDM"), false, 28),
            RadioStation("Tiesto", "https://radiorecord.hostingradio.ru/tiesto96.aacp", R.drawable.icon30, "https://www.radiorecord.ru/api/station/history/?id=43696", listOf("EDM", "House"), false, 29),
            RadioStation("David Guetta", "https://radiorecord.hostingradio.ru/guetta96.aacp", R.drawable.icon31, "https://www.radiorecord.ru/api/station/history/?id=43695", listOf("EDM", "House"), false, 30),
            RadioStation("Armin Van Buuren", "https://radiorecord.hostingradio.ru/armin96.aacp", R.drawable.icon32, "https://www.radiorecord.ru/api/station/history/?id=43697", listOf("Trance", "EDM"), false, 31),
            RadioStation("Record Chill-Out", "https://radiorecord.hostingradio.ru/chil96.aacp", R.drawable.icon33, "https://www.radiorecord.ru/api/station/history/?id=534", listOf("Chill", "EDM"), false, 32),
            RadioStation("Record Dancecore", "https://radiorecord.hostingradio.ru/dc96.aacp", R.drawable.icon34, "https://www.radiorecord.ru/api/station/history/?id=546", listOf("Dance", "Hard"), false, 33),
            RadioStation("Record Deep", "https://radiorecord.hostingradio.ru/deep96.aacp", R.drawable.icon35, "https://www.radiorecord.ru/api/station/history/?id=528", listOf("Deep", "House"), false, 34),
            RadioStation("Record Dubstep", "https://radiorecord.hostingradio.ru/dub96.aacp", R.drawable.icon36, "https://www.radiorecord.ru/api/station/history/?id=545", listOf("Breaks", "Bass"), false, 35),
            RadioStation("Record Future House", "https://radiorecord.hostingradio.ru/fut96.aacp", R.drawable.icon37, "https://www.radiorecord.ru/api/station/history/?id=532", listOf("Future House", "EDM"), false, 36),
            RadioStation("Record Goa/Psy", "https://radiorecord.hostingradio.ru/goa96.aacp", R.drawable.icon38, "https://www.radiorecord.ru/api/station/history/?id=531", listOf("Hard", "Trance"), false, 37),
            RadioStation("Record Hardstyle", "https://radiorecord.hostingradio.ru/teo96.aacp", R.drawable.icon39, "https://www.radiorecord.ru/api/station/history/?id=550", listOf("Hard", "EDM"), false, 38),
            RadioStation("Record Minimal/Tech", "https://radiorecord.hostingradio.ru/mini96.aacp", R.drawable.icon40, "https://www.radiorecord.ru/api/station/history/?id=535", listOf("Другое", "Techno"), false, 39),
            RadioStation("Record Techno", "https://radiorecord.hostingradio.ru/techno96.aacp", R.drawable.icon41, "https://www.radiorecord.ru/api/station/history/?id=547", listOf("Techno", "EDM"), false, 40),
            RadioStation("Record Tropical", "https://radiorecord.hostingradio.ru/trop96.aacp", R.drawable.icon42, "https://www.radiorecord.ru/api/station/history/?id=530", listOf("Trance", "EDM"), false, 41),
            RadioStation("Record Uplifting", "https://radiorecord.hostingradio.ru/uplift96.aacp", R.drawable.icon43, "https://www.radiorecord.ru/api/station/history/?id=504", listOf("Techno", "Trance"), false, 42),
            RadioStation("Record Big Hits", "https://radiorecord.hostingradio.ru/bighits96.aacp", R.drawable.icon44, "https://www.radiorecord.ru/api/station/history/?id=501", listOf("Oldschool", "EDM"), false, 43),
            RadioStation("Record Breaks", "https://radiorecord.hostingradio.ru/brks96.aacp", R.drawable.icon45, "https://www.radiorecord.ru/api/station/history/?id=544", listOf("Breaks", "Bass"), false, 44),
            RadioStation("Record Black Rap", "https://radiorecord.hostingradio.ru/rap96.aacp", R.drawable.icon46, "https://www.radiorecord.ru/api/station/history/?id=558", listOf("Rap/Urban", "Bass"), false, 45),
            RadioStation("Record Lady Waks", "https://radiorecord.hostingradio.ru/ladywaks96.aacp", R.drawable.icon47, "https://www.radiorecord.ru/api/station/history/?id=44167", listOf("Bass", "EDM"), false, 46),
            RadioStation("Record Neurofunk", "https://radiorecord.hostingradio.ru/neurofunk96.aacp", R.drawable.icon48, "https://www.radiorecord.ru/api/station/history/?id=507", listOf("Drum", "Bass"), false, 47),
            RadioStation("Радио ENERGY", "https://srv02.gpmradio.ru:8443/stream/air/aac/64/99", R.drawable.icon49, "https://101.ru/api/channel/getTrackOnAir/99/channel/?dataFormat=json", listOf("Pop", "EDM"), false, 48),
            RadioStation("Record Darkside", "https://radiorecord.hostingradio.ru/darkside96.aacp", R.drawable.icon50, "https://www.radiorecord.ru/api/station/history/?id=503", listOf("Drum", "EDM"), false, 49),
            RadioStation("Record Party", "https://radiorecord.hostingradio.ru/party96.aacp", R.drawable.icon51, "https://www.radiorecord.ru/api/station/history/?id=42891", listOf("Party", "EDM"), false, 50),
            RadioStation("Сказки MC V", "https://radiorecord.hostingradio.ru/skazki96.aacp", R.drawable.icon52, "https://www.radiorecord.ru/api/station/history/?id=44373", listOf("Pop", "Rus"), false, 51),
            RadioStation("Супердискотека 90-х", "https://radiorecord.hostingradio.ru/sd9096.aacp", R.drawable.icon53, "https://www.radiorecord.ru/api/station/history/?id=539", listOf("Oldschool", "Dance"), false, 52),
            RadioStation("Summer Dance", "https://radiorecord.hostingradio.ru/summerparty96.aacp", R.drawable.icon54, "https://www.radiorecord.ru/api/station/history/?id=42725", listOf("Dance", "EDM"), false, 53),
            RadioStation("Beach Party", "https://radiorecord.hostingradio.ru/beach96.aacp", R.drawable.icon55, "https://www.radiorecord.ru/api/station/history/?id=44331", listOf("Dance", "EDM"), false, 54),
            RadioStation("Russian Hits", "https://radiorecord.hostingradio.ru/rus96.aacp", R.drawable.icon56, "https://www.radiorecord.ru/api/station/history/?id=519", listOf("Rus", "Pop"), false, 55),
            RadioStation("Festivals", "https://radiorecord.hostingradio.ru/livedjsets96.aacp", R.drawable.icon57, "https://www.radiorecord.ru/api/station/history/?id=43173", listOf("EDM", "Dance"), false, 56),
            RadioStation("NRJ Club Dance", "https://pub0202.101.ru:8000/stream/trust/mp3/128/5?", R.drawable.icon58, "unknown", listOf("EDM", "Dance"), false, 57),
            RadioStation("На шашлыки!", "https://radiorecord.hostingradio.ru/nashashlyki96.aacp", R.drawable.icon59, "https://www.radiorecord.ru/api/station/history/?id=43817", listOf("Pop", "Rus"), false, 58),
            RadioStation("Rock", "https://radiorecord.hostingradio.ru/rock96.aacp", R.drawable.icon60, "https://www.radiorecord.ru/api/station/history/?id=554", listOf("Rock", "Pop"), false, 59),
            RadioStation("Гоп FM", "https://radiorecord.hostingradio.ru/gop96.aacp", R.drawable.icon61, "https://www.radiorecord.ru/api/station/history/?id=556", listOf("Pop", "Rus"), false, 60),
            RadioStation("Chill House", "https://radiorecord.hostingradio.ru/chillhouse96.aacp", R.drawable.icon62, "https://www.radiorecord.ru/api/station/history/?id=515", listOf("Chill", "House"), false, 61),
            RadioStation("Рекорд 00-х", "https://radiorecord.hostingradio.ru/200096.aacp", R.drawable.icon63, "https://www.radiorecord.ru/api/station/history/?id=43264", listOf("Oldschool", "Pop"), false, 62),
            RadioStation("Record 80-х", "https://radiorecord.hostingradio.ru/198096.aacp", R.drawable.icon64, "https://www.radiorecord.ru/api/station/history/?id=514", listOf("Oldschool", "Pop"), false, 63),
            RadioStation("Нафталин FM", "https://radiorecord.hostingradio.ru/naft96.aacp", R.drawable.icon65, "https://www.radiorecord.ru/api/station/history/?id=561", listOf("Oldschool", "Pop"), false, 64),
            RadioStation("Маятник Фуко (18+)", "https://radiorecord.hostingradio.ru/mf96.aacp", R.drawable.icon66, "https://www.radiorecord.ru/api/station/history/?id=495", listOf("Rap/Urban", "Rus"), false, 65),
            RadioStation("Trancemission", "https://radiorecord.hostingradio.ru/tm96.aacp", R.drawable.icon67, "https://www.radiorecord.ru/api/station/history/?id=533", listOf("Trance", "EDM"), false, 66),
            RadioStation("Russian Gold", "https://radiorecord.hostingradio.ru/russiangold96.aacp", R.drawable.icon68, "https://www.radiorecord.ru/api/station/history/?id=524", listOf("Rus", "Oldschool"), false, 67),
            RadioStation("Pirate Station", "https://radiorecord.hostingradio.ru/ps96.aacp", R.drawable.icon69, "https://www.radiorecord.ru/api/station/history/?id=536", listOf("EDM", "Bass"), false, 68),
            RadioStation("Innocence", "https://radiorecord.hostingradio.ru/ibiza96.aacp", R.drawable.icon70, "https://www.radiorecord.ru/api/station/history/?id=494", listOf("Techno", "House"), false, 69),
            RadioStation("Медляк FM", "https://radiorecord.hostingradio.ru/mdl96.aacp", R.drawable.icon71, "https://www.radiorecord.ru/api/station/history/?id=555", listOf("Chill", "Pop"), false, 70),
            RadioStation("Дорожное Радио", "https://dorognoe.hostingradio.ru/dorognoe", R.drawable.icon72, "unknown", listOf("Pop", "Rus"), false, 71),
            RadioStation("Руки Вверх!", "https://radiorecord.hostingradio.ru/rv96.aacp", R.drawable.icon73, "https://www.radiorecord.ru/api/station/history/?id=14954", listOf("Pop", "Rus"), false, 72),
            RadioStation("На Хайпе", "https://radiorecord.hostingradio.ru/hype96.aacp", R.drawable.icon74, "https://www.radiorecord.ru/api/station/history/?id=43455", listOf("Pop", "Rus"), false, 73),
            RadioStation("Rap Hits", "https://radiorecord.hostingradio.ru/rap96.aacp", R.drawable.icon75, "https://www.radiorecord.ru/api/station/history/?id=511", listOf("Rap/Urban", "Oldschool"), false, 74),
            RadioStation("Rap Classics", "https://radiorecord.hostingradio.ru/rapclassics96.aacp", R.drawable.icon76, "https://www.radiorecord.ru/api/station/history/?id=512", listOf("Rap/Urban", "Oldschool"), false, 75),
            RadioStation("Trance Classics", "https://radiorecord.hostingradio.ru/trancehits96.aacp", R.drawable.icon77, "https://www.radiorecord.ru/api/station/history/?id=510", listOf("Trance", "Classics"), false, 76),
            RadioStation("Колбасный Цех", "https://radiorecord.hostingradio.ru/pump96.aacp", R.drawable.icon78, "https://www.radiorecord.ru/api/station/history/?id=553", listOf("EDM", "Bass"), false, 77),
            RadioStation("D'n'B Classics", "https://radiorecord.hostingradio.ru/drumhits96.aacp", R.drawable.icon79, "https://www.radiorecord.ru/api/station/history/?id=523", listOf("Drum", "Bass"), false, 78),
            RadioStation("Summer Lounge", "https://radiorecord.hostingradio.ru/summerlounge96.aacp", R.drawable.icon81, "https://www.radiorecord.ru/api/station/history/?id=43337", listOf("Chill", "Trance"), false, 80),
            RadioStation("Organic", "https://radiorecord.hostingradio.ru/organic96.aacp", R.drawable.icon82, "https://www.radiorecord.ru/api/station/history/?id=42715", listOf("Chill", "Trance"), false, 81),
            RadioStation("Ultra Music Festival", "https://radiorecord.hostingradio.ru/ultra96.aacp", R.drawable.icon83, "https://www.radiorecord.ru/api/station/history/?id=44215", listOf("EDM", "Dance"), false, 82),
            RadioStation("VIP House", "https://radiorecord.hostingradio.ru/vip96.aacp", R.drawable.icon84, "https://www.radiorecord.ru/api/station/history/?id=538", listOf("House", "EDM"), false, 83),
            RadioStation("Liquid Funk", "https://radiorecord.hostingradio.ru/liquidfunk96.aacp", R.drawable.icon85, "https://www.radiorecord.ru/api/station/history/?id=522", listOf("Drum", "Bass"), false, 84),
            RadioStation("Bass House", "https://radiorecord.hostingradio.ru/jackin96.aacp", R.drawable.icon86, "https://www.radiorecord.ru/api/station/history/?id=541", listOf("Bass", "House"), false, 85),
            RadioStation("10's Dance", "https://radiorecord.hostingradio.ru/201096.aacp", R.drawable.icon87, "https://www.radiorecord.ru/api/station/history/?id=43451", listOf("Dance", "Oldschool"), false, 86),
            RadioStation("Trancehouse", "https://radiorecord.hostingradio.ru/trancehouse96.aacp", R.drawable.icon88, "https://www.radiorecord.ru/api/station/history/?id=542", listOf("Trance", "House"), false, 87),
            RadioStation("Lo-Fi", "https://radiorecord.hostingradio.ru/lofi96.aacp", R.drawable.icon89, "https://www.radiorecord.ru/api/station/history/?id=42532", listOf("Trance", "Chill"), false, 88),
            RadioStation("Tech House", "https://radiorecord.hostingradio.ru/techouse96.aacp", R.drawable.icon90, "https://www.radiorecord.ru/api/station/history/?id=42509", listOf("Techno", "House"), false, 89),
            RadioStation("Technopop", "https://radiorecord.hostingradio.ru/technopop96.aacp", R.drawable.icon92, "https://www.radiorecord.ru/api/station/history/?id=526", listOf("Techno", "Pop"), false, 91),
            RadioStation("70's Dance", "https://radiorecord.hostingradio.ru/197096.aacp", R.drawable.icon93, "https://www.radiorecord.ru/api/station/history/?id=516", listOf("Oldschool", "Dance"), false, 92),
            RadioStation("Dream Dance", "https://radiorecord.hostingradio.ru/dream96.aacp", R.drawable.icon94, "https://www.radiorecord.ru/api/station/history/?id=502", listOf("Другое", "Dance"), false, 93),
            RadioStation("Ambient", "https://radiorecord.hostingradio.ru/ambient96.aacp", R.drawable.icon95, "https://www.radiorecord.ru/api/station/history/?id=42650", listOf("Trance", "Chill"), false, 94),
            RadioStation("Record Classix", "https://radiorecord.hostingradio.ru/classix96.aacp", R.drawable.icon96, "https://www.radiorecord.ru/api/station/history/?id=44183", listOf("Oldschool", "EDM"), false, 95),
            RadioStation("Record Club Show", "https://radiorecord.hostingradio.ru/clubshow96.aacp", R.drawable.icon97, "https://www.radiorecord.ru/api/station/history/?id=44188", listOf("Dance", "EDM"), false, 96),
            RadioStation("Eurodance", "https://radiorecord.hostingradio.ru/eurodance96.aacp", R.drawable.icon98, "https://www.radiorecord.ru/api/station/history/?id=525", listOf("Dance", "EDM"), false, 97),
            RadioStation("Lo-Fi House", "https://radiorecord.hostingradio.ru/lofihouse96.aacp", R.drawable.icon99, "https://www.radiorecord.ru/api/station/history/?id=43925", listOf("Dance", "House"), false, 98),
            RadioStation("Feel", "https://radiorecord.hostingradio.ru/feel96.aacp", R.drawable.icon101, "https://www.radiorecord.ru/api/station/history/?id=44168", listOf("Chill", "EDM"), false, 100),
            RadioStation("A State of Trance", "https://radiorecord.hostingradio.ru/asot96.aacp", R.drawable.icon102, "https://www.radiorecord.ru/api/station/history/?id=44166", listOf("Trance", "EDM"), false, 101),
            RadioStation("Веснушка FM", "https://radiorecord.hostingradio.ru/deti96.aacp", R.drawable.icon103, "https://www.radiorecord.ru/api/station/history/?id=15076", listOf("Pop", "Rus"), false, 102),
            RadioStation("TOP 100 EDM", "https://radiorecord.hostingradio.ru/top100edm96.aacp", R.drawable.icon105, "https://www.radiorecord.ru/api/station/history/?id=43172", listOf("EDM", "Hits"), false, 104),
            RadioStation("Dream Pop", "https://radiorecord.hostingradio.ru/dreampop96.aacp", R.drawable.icon106, "https://www.radiorecord.ru/api/station/history/?id=42602", listOf("Другое", "Pop"), false, 105),
            RadioStation("House Classics", "https://radiorecord.hostingradio.ru/houseclassics96.aacp", R.drawable.icon107, "https://www.radiorecord.ru/api/station/history/?id=505", listOf("House", "Oldschool"), false, 106),
            RadioStation("DJ Цветкоff", "https://radiorecord.hostingradio.ru/tsvetkov96.aacp", R.drawable.icon108, "https://www.radiorecord.ru/api/station/history/?id=44212", listOf("EDM", "House"), false, 107),
            RadioStation("Disco/Funk", "https://radiorecord.hostingradio.ru/discofunk96.aacp", R.drawable.icon109, "https://www.radiorecord.ru/api/station/history/?id=527", listOf("Oldschool", "Другое"), false, 108),
            RadioStation("Hard Bass", "https://radiorecord.hostingradio.ru/hbass96.aacp", R.drawable.icon110, "https://www.radiorecord.ru/api/station/history/?id=551", listOf("Hard", "Bass"), false, 109),
            RadioStation("Afro House", "https://radiorecord.hostingradio.ru/afro96.aacp", R.drawable.icon111, "https://www.radiorecord.ru/api/station/history/?id=43927", listOf("Другое","Rap/Urban", "House"), false, 110),
            RadioStation("Rave FM", "https://radiorecord.hostingradio.ru/rave96.aacp", R.drawable.icon112, "https://www.radiorecord.ru/api/station/history/?id=559", listOf("Rave", "EDM"), false, 111),
            RadioStation("Nu Dance", "https://radiorecord.hostingradio.ru/nudance96.aacp", R.drawable.icon113, "https://www.radiorecord.ru/api/station/history/?id=43926", listOf("Dance", "EDM"), false, 112),
            RadioStation("60's Dance", "https://radiorecord.hostingradio.ru/196096.aacp", R.drawable.icon114, "https://www.radiorecord.ru/api/station/history/?id=513", listOf("Oldschool", "Dance"), false, 113),
            RadioStation("Progressive", "https://radiorecord.hostingradio.ru/progr96.aacp", R.drawable.icon115, "https://www.radiorecord.ru/api/station/history/?id=498", listOf("Trance", "House"), false, 114),
            RadioStation("Nejtrino & Baur", "https://radiorecord.hostingradio.ru/nejtrinobaur96.aacp", R.drawable.icon116, "https://www.radiorecord.ru/api/station/history/?id=44209", listOf("EDM", "House"), false, 115),
            RadioStation("Synthwave", "https://radiorecord.hostingradio.ru/synth96.aacp", R.drawable.icon117, "https://www.radiorecord.ru/api/station/history/?id=499", listOf("Oldschool", "EDM"), false, 116),
            RadioStation("Latina Dance", "https://radiorecord.hostingradio.ru/latina96.aacp", R.drawable.icon118, "https://www.radiorecord.ru/api/station/history/?id=43452", listOf("Другое", "Dance"), false, 117),
            RadioStation("DJ Gvozd", "https://radiorecord.hostingradio.ru/djgvozd96.aacp", R.drawable.icon119, "https://www.radiorecord.ru/api/station/history/?id=44187", listOf("Rap/Urban", "Bass"), false, 118),
            RadioStation("Tecktonik", "https://radiorecord.hostingradio.ru/tecktonik96.aacp", R.drawable.icon121, "https://www.radiorecord.ru/api/station/history/?id=508", listOf("Techno", "Dance"), false, 120),
            RadioStation("Jungle", "https://radiorecord.hostingradio.ru/jungle96.aacp", R.drawable.icon122, "https://www.radiorecord.ru/api/station/history/?id=521", listOf("Drum", "Bass"), false, 121),
            RadioStation("Hypnotic", "https://radiorecord.hostingradio.ru/hypno96.aacp", R.drawable.icon123, "https://www.radiorecord.ru/api/station/history/?id=543", listOf("Drum", "EDM"), false, 122),
            RadioStation("UK Garage", "https://radiorecord.hostingradio.ru/ukgarage96.aacp", R.drawable.icon124, "https://www.radiorecord.ru/api/station/history/?id=544", listOf("Dance", "Breaks"), false, 123),
            RadioStation("Гастарбайтер FM", "https://radiorecord.hostingradio.ru/gast96.aacp", R.drawable.icon125, "https://www.radiorecord.ru/api/station/history/?id=560", listOf("Pop", "Rus"), false, 124),
            RadioStation("Midtempo", "https://radiorecord.hostingradio.ru/mt96.aacp", R.drawable.icon126, "https://www.radiorecord.ru/api/station/history/?id=497", listOf("Bass", "EDM"), false, 125),
            RadioStation("Future Bass", "https://radiorecord.hostingradio.ru/fbass96.aacp", R.drawable.icon127, "https://www.radiorecord.ru/api/station/history/?id=549", listOf("EDM", "Bass"), false, 126),
            RadioStation("Martin Garrix", "https://radiorecord.hostingradio.ru/martingarrix96.aacp", R.drawable.icon128, "https://www.radiorecord.ru/api/station/history/?id=44211", listOf("EDM", "House"), false, 127),
            RadioStation("Русская Зима", "https://radiorecord.hostingradio.ru/ruszima96.aacp", R.drawable.icon129, "https://www.radiorecord.ru/api/station/history/?id=43601", listOf("Rus", "Pop"), false, 128),
            RadioStation("Oliver Heldens", "https://radiorecord.hostingradio.ru/oliverheldens96.aacp", R.drawable.icon130, "https://www.radiorecord.ru/api/station/history/?id=44210", listOf("House", "EDM"), false, 129),
            RadioStation("Moombahton", "https://radiorecord.hostingradio.ru/mmbt96.aacp", R.drawable.icon131, "https://www.radiorecord.ru/api/station/history/?id=540", listOf("Pop", "EDM"), false, 130),
            RadioStation("2-step", "https://radiorecord.hostingradio.ru/2step96.aacp", R.drawable.icon132, "https://www.radiorecord.ru/api/station/history/?id=509", listOf("2-step", "Bass"), false, 131),
            RadioStation("Complextro", "https://radiorecord.hostingradio.ru/complextro96.aacp", R.drawable.icon133, "https://www.radiorecord.ru/api/station/history/?id=517", listOf("House", "Другое"), false, 132),
            RadioStation("Groove/Tribal", "https://radiorecord.hostingradio.ru/groovetribal96.aacp", R.drawable.icon134, "https://www.radiorecord.ru/api/station/history/?id=518", listOf("House", "Tribal"), false, 133)
        )
    }
}
